<a href="https://colab.research.google.com/github/andrewdaotran/learning_pytorch_colab_notebook/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

PyTorch Documentation: https://pytorch.org


### Getting Setup with Google Colab
  * https://colab.research.google.com
  * Can use a free GPU provided by Google
    * Runtime > Change Runtime Type > GPU
    * A lot faster for computing time especially for deep learning

    * Ctrl + M + M (Might be Cmd + M + M on other macs)
      * Turns code cell into text cell

`!nvidia-smi` = shows us which GPU you are using

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


`print(torch.__version__) = shows us what version of PyTorch we have

`1.13.1+cu116`
* Version + CUDA version

### Introduction to Tensors

#### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

`Tensor.ndim` =  How to check how many dimensions are in the tensor

Easy way to determine how many dimensions a tensor has on your own is to see how many nested `[ square brackets ]` there are

In [8]:
scalar.item()

7

`scalar.item()` = get tensor back as Python int

In [9]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

`Tensor.shape` = 

In [14]:
# MATRIX 
MATRIX = torch.tensor([[7, 8],
                        [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [17]:
MATRIX[0]

tensor([7, 8])

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
TENSOR[0][1]

tensor([4, 5, 6])

In [29]:
TENSOR[0][2][2]

tensor(9)

In [41]:
TENSOR_PRACTICE = torch.tensor([[[2, 5, 0],
                                 [1, 2, 7],
                                 [4, 7, 1]],
                                [[2, 5, 3],
                                 [7, 3, 2],
                                 [8, 9, 1]]])
TENSOR_PRACTICE

tensor([[[2, 5, 0],
         [1, 2, 7],
         [4, 7, 1]],

        [[2, 5, 3],
         [7, 3, 2],
         [8, 9, 1]]])

In [33]:
TENSOR_PRACTICE.ndim

3

In [34]:
TENSOR_PRACTICE.shape

torch.Size([2, 3, 3])

### Random tensors 

Why random tensors? 

Random tesnsors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers > look at data > update random numbers > look at data > update random numbers`

Torch random tensors = https://pytorch.org/docs/stable/generated/torch.rand.html



In [48]:
# Create a random tensor with PyTorch
# Tensor of size/shape (3, 5)
random_tensor = torch.rand(3, 5)
random_tensor

tensor([[0.1031, 0.4881, 0.9863, 0.3119, 0.1608],
        [0.5266, 0.8261, 0.2363, 0.9649, 0.7606],
        [0.6949, 0.6013, 0.8070, 0.3519, 0.3351]])

In [49]:
random_tensor.ndim

2

In [52]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #  color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Almost any data can be represented as a tensor and one of the common ways to represent an image is in the format color, height, width

### Zeros and Ones Tensor


In [55]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
# Create a tensor of all ones 
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [56]:
ones.dtype

torch.float32

`Tensor.dtype` = Gives you the data type of your tensor

The default data type of a PyTorch tensor is `torch.float`

### Creating a range of tensors and tensors-like

`torch.arange()` documentation = https://pytorch.org/docs/stable/generated/torch.arange.html


In [68]:
# Use torch.range() and get deprecated message, use torch.arange() instead
torch.range(0, 10)

<ipython-input-68-16053d63d4b2>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [66]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])