<a href="https://colab.research.google.com/github/andrewdaotran/learning_pytorch_colab_notebook/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

PyTorch Documentation: https://pytorch.org


### Getting Setup with Google Colab
  * https://colab.research.google.com
  * Can use a free GPU provided by Google
    * Runtime > Change Runtime Type > GPU
    * A lot faster for computing time especially for deep learning

    * Ctrl + M + M (Might be Cmd + M + M on other macs)
      * Turns code cell into text cell

`!nvidia-smi` = shows us which GPU you are using

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


`print(torch.__version__) = shows us what version of PyTorch we have

`1.13.1+cu116`
* Version + CUDA version

### Introduction to Tensors

#### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [7]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

`Tensor.ndim` =  How to check how many dimensions are in the tensor

Easy way to determine how many dimensions a tensor has on your own is to see how many nested `[ square brackets ]` there are

In [ ]:
scalar.item()

7

`scalar.item()` = get tensor back as Python int

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

`Tensor.shape` = 

In [ ]:
# MATRIX 
MATRIX = torch.tensor([[7, 8],
                        [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][1]

tensor([4, 5, 6])

In [ ]:
TENSOR[0][2][2]

tensor(9)

In [ ]:
TENSOR_PRACTICE = torch.tensor([[[2, 5, 0],
                                 [1, 2, 7],
                                 [4, 7, 1]],
                                [[2, 5, 3],
                                 [7, 3, 2],
                                 [8, 9, 1]]])
TENSOR_PRACTICE

tensor([[[2, 5, 0],
         [1, 2, 7],
         [4, 7, 1]],

        [[2, 5, 3],
         [7, 3, 2],
         [8, 9, 1]]])

In [ ]:
TENSOR_PRACTICE.ndim

3

In [ ]:
TENSOR_PRACTICE.shape

torch.Size([2, 3, 3])

### Random tensors 

Why random tensors? 

Random tesnsors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers > look at data > update random numbers > look at data > update random numbers`

Torch random tensors = https://pytorch.org/docs/stable/generated/torch.rand.html



In [ ]:
# Create a random tensor with PyTorch
# Tensor of size/shape (3, 5)
random_tensor = torch.rand(3, 5)
random_tensor

tensor([[0.1031, 0.4881, 0.9863, 0.3119, 0.1608],
        [0.5266, 0.8261, 0.2363, 0.9649, 0.7606],
        [0.6949, 0.6013, 0.8070, 0.3519, 0.3351]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #  color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Almost any data can be represented as a tensor and one of the common ways to represent an image is in the format color, height, width

### Zeros and Ones Tensor


In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones 
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

`Tensor.dtype` = Gives you the data type of your tensor

The default data type of a PyTorch tensor is `torch.float`

### Creating a range of tensors and tensors-like

`torch.arange()` documentation = https://pytorch.org/docs/stable/generated/torch.arange.html


In [ ]:
# Use torch.range() and get deprecated message, use torch.arange() instead
torch.range(0, 10)

<ipython-input-68-16053d63d4b2>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big **errors** with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

Most common datatypes you will see are `32-bit floating point` and `16-bit floating point`

These numbers have to do with precision in computing

The `precision` of a numerical quantity is a measure of the detail in which the quantity is expressed. This is usually measured in bits, but sometimes in decimal digits. It is related to precision in mathematics, which describes the number of digits that are used to express a value. - Wikipedia for `Precision (computer science)`
* https://en.wikipedia.org/wiki/Precision_(computer_science)

Float32 (occupying 32 bits in computer memory) = `single-precision floating-point format`

Float16 = `half-precision floating-point format`

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # What datatype the tensor is (e.g, float32 or float16)
                               device=None, # What device is your tensor on; cpu by default
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16) #can use torch.half instead of torch.float16
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)



1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
  * `tensor.size()` is a function while `tensor.shape` is an attribute; can give us the same result
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`

In [8]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8824, 0.7712, 0.3677, 0.7242],
        [0.8100, 0.0432, 0.9525, 0.0119],
        [0.8747, 0.7867, 0.5715, 0.2152]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.9338, 0.9142, 0.3432, 0.7365],
        [0.9407, 0.9898, 0.9795, 0.1233],
        [0.3807, 0.3592, 0.8098, 0.6951]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include: 
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication






In [4]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [10]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [11]:
# Subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [16]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10) # same as tensor * 10

tensor([10, 20, 30])

`torch.mul()` = multiplying; simply insert what you want to multiply and by what to get your result

In [17]:
torch.add(tensor, 10) # same as tensor + 10

tensor([11, 12, 13])

`torch.add()` = adding

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)
  * The most common tensor operation you will find in neural networks

How to multiply matrices by Math is Fun
  * https://www.mathsisfun.com/algebra/matrix-multiplying.html


#### There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` Won't work
* `(3, 2) @ (2, 3)` Will work
  * @ symbol is an operater used for matrix multiplication

2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [20]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) # Won't work

RuntimeError: ignored

In [21]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)) # Will work 

tensor([[0.7203, 0.9905, 0.6594],
        [1.0579, 1.1671, 1.0894],
        [0.5229, 0.6066, 0.5259]])

In [22]:
tensor

tensor([1, 2, 3])

In [18]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [8]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [13]:
# Matrix multiplication by hand
%%time
1*1 + 2*2 + 3*3

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 8.11 µs


14

In [14]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value
# for loop 10x slower than torch.matmul() method even on a small matrix

CPU times: user 1.7 ms, sys: 0 ns, total: 1.7 ms
Wall time: 1.45 ms


tensor(14)

In [12]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 374 µs, sys: 15 µs, total: 389 µs
Wall time: 396 µs


tensor(14)

### One of the most common errors in deep learning: Shape Errors

In [4]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                          [8, 11],
                          [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul # won't work due to shape error


RuntimeError: ignored

To fix our tensor shape issues, we can manipulate teh shape of one of our tensors using a **transpose**

A **transpose** swithces the axes or dimensions of a given tensor

In [8]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]), torch.Size([3, 2]))

In [10]:
tensor_B.T, tensor_B.T.shape # Tensor.T will transpose the tensor into the flipped dimension 3 x 2 -> 2 x 3

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [16]:
# Now the multiplication will work because tensor_B has been transposed and the two tensors fit the first rule of matrix multiplication
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
