<a href="https://colab.research.google.com/github/andrewdaotran/learning_pytorch_colab_notebook/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

`If your runtime has timed out you can restart your runtime by going to Runtime > Run all / Restart and run all / etc. > Yes`

`If you left in errors on purpose, Run all / Restart and run all will stop at the errors so you must do Runtime > Run after in order to run the cells after the error`

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

PyTorch Documentation: https://pytorch.org


### Getting Setup with Google Colab
  * https://colab.research.google.com
  * Can use a free GPU provided by Google
    * Runtime > Change Runtime Type > GPU
    * A lot faster for computing time especially for deep learning

    * Ctrl + M + M (Might be Cmd + M + M on other macs)
      * Turns code cell into text cell

`!nvidia-smi` = shows us which GPU you are using

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


`print(torch.__version__) = shows us what version of PyTorch we have

`1.13.1+cu116`
* Version + CUDA version

### Introduction to Tensors

#### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

`Tensor.ndim` =  How to check how many dimensions are in the tensor

Easy way to determine how many dimensions a tensor has on your own is to see how many nested `[ square brackets ]` there are

In [4]:
scalar.item()

7

`scalar.item()` = get tensor back as Python int

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

`Tensor.shape` = 

In [8]:
# MATRIX 
MATRIX = torch.tensor([[7, 8],
                        [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
TENSOR[0][1]

tensor([4, 5, 6])

In [17]:
TENSOR[0][2][2]

tensor(9)

In [18]:
TENSOR_PRACTICE = torch.tensor([[[2, 5, 0],
                                 [1, 2, 7],
                                 [4, 7, 1]],
                                [[2, 5, 3],
                                 [7, 3, 2],
                                 [8, 9, 1]]])
TENSOR_PRACTICE

tensor([[[2, 5, 0],
         [1, 2, 7],
         [4, 7, 1]],

        [[2, 5, 3],
         [7, 3, 2],
         [8, 9, 1]]])

In [19]:
TENSOR_PRACTICE.ndim

3

In [20]:
TENSOR_PRACTICE.shape

torch.Size([2, 3, 3])

### Random tensors 

Why random tensors? 

Random tesnsors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers > look at data > update random numbers > look at data > update random numbers`

Torch random tensors = https://pytorch.org/docs/stable/generated/torch.rand.html



In [21]:
# Create a random tensor with PyTorch
# Tensor of size/shape (3, 5)
random_tensor = torch.rand(3, 5)
random_tensor

tensor([[0.6958, 0.7928, 0.5048, 0.5283, 0.4842],
        [0.9983, 0.6565, 0.4349, 0.7343, 0.1472],
        [0.2993, 0.3141, 0.6325, 0.0972, 0.3522]])

In [22]:
random_tensor.ndim

2

In [23]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #  color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Almost any data can be represented as a tensor and one of the common ways to represent an image is in the format color, height, width

### Zeros and Ones Tensor


In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Create a tensor of all ones 
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

`Tensor.dtype` = Gives you the data type of your tensor

The default data type of a PyTorch tensor is `torch.float`

### Creating a range of tensors and tensors-like

`torch.arange()` documentation = https://pytorch.org/docs/stable/generated/torch.arange.html


In [27]:
# Use torch.range() and get deprecated message, use torch.arange() instead
torch.range(0, 10)

<ipython-input-27-16053d63d4b2>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big **errors** with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

Most common datatypes you will see are `32-bit floating point` and `16-bit floating point`

These numbers have to do with precision in computing

The `precision` of a numerical quantity is a measure of the detail in which the quantity is expressed. This is usually measured in bits, but sometimes in decimal digits. It is related to precision in mathematics, which describes the number of digits that are used to express a value. - Wikipedia for `Precision (computer science)`
* https://en.wikipedia.org/wiki/Precision_(computer_science)

Float32 (occupying 32 bits in computer memory) = `single-precision floating-point format`

Float16 = `half-precision floating-point format`

In [30]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # What datatype the tensor is (e.g, float32 or float16)
                               device=None, # What device is your tensor on; cpu by default
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16) #can use torch.half instead of torch.float16
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)



1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
  * `tensor.size()` is a function while `tensor.shape` is an attribute; can give us the same result
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`

In [33]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8810, 0.0037, 0.9672, 0.4189],
        [0.0908, 0.9267, 0.1454, 0.1135],
        [0.3752, 0.8011, 0.7534, 0.2819]])

In [34]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.8810, 0.0037, 0.9672, 0.4189],
        [0.0908, 0.9267, 0.1454, 0.1135],
        [0.3752, 0.8011, 0.7534, 0.2819]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include: 
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication






In [35]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [36]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [37]:
# Subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [38]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10) # same as tensor * 10

tensor([10, 20, 30])

`torch.mul()` = multiplying; simply insert what you want to multiply and by what to get your result

In [39]:
torch.add(tensor, 10) # same as tensor + 10

tensor([11, 12, 13])

`torch.add()` = adding

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)
  * The most common tensor operation you will find in neural networks

How to multiply matrices by Math is Fun
  * https://www.mathsisfun.com/algebra/matrix-multiplying.html


#### There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` Won't work
* `(3, 2) @ (2, 3)` Will work
  * @ symbol is an operater used for matrix multiplication

2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [41]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) # Won't work

RuntimeError: ignored

In [42]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)) # Will work 

tensor([[0.6445, 0.0752, 0.2990],
        [0.5425, 0.3254, 0.3330],
        [0.6053, 0.1825, 0.3155]])

In [43]:
tensor

tensor([1, 2, 3])

In [44]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [45]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [46]:
# Matrix multiplication by hand
%%time
1*1 + 2*2 + 3*3

CPU times: user 23 µs, sys: 3 µs, total: 26 µs
Wall time: 52.2 µs


14

In [47]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value
# for loop 10x slower than torch.matmul() method even on a small matrix

CPU times: user 827 µs, sys: 17 µs, total: 844 µs
Wall time: 3.16 ms


tensor(14)

In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 120 µs, sys: 0 ns, total: 120 µs
Wall time: 126 µs


tensor(14)

### One of the most common errors in deep learning: Shape Errors

In [50]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                          [8, 11],
                          [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul # won't work due to shape error


RuntimeError: ignored

To fix our tensor shape issues, we can manipulate teh shape of one of our tensors using a **transpose**

A **transpose** swithces the axes or dimensions of a given tensor

In [51]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]), torch.Size([3, 2]))

In [52]:
tensor_B.T, tensor_B.T.shape # Tensor.T will transpose the tensor into the flipped dimension 3 x 2 -> 2 x 3

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [53]:
# Now the multiplication will work because tensor_B has been transposed and the two tensors fit the first rule of matrix multiplication
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [54]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [55]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [56]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [58]:
# Find the mean (Wrong)
torch.mean(x), x.mean() # Won't work due to wrong tensor datatype

RuntimeError: ignored

In [59]:
x.dtype # int64 = long

torch.int64

In [60]:
# Find the mean (Correct) - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # Now will work because we changed the datatype

(tensor(46.), tensor(46.))

In [61]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [62]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [63]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor were the minimum value occurs
x.argmin()

tensor(0)

In [64]:
# Checking the value of the minimum value of our tensor with the provided index from Tensor.argmin()
x[0]

tensor(1)

In [65]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [66]:
# Checking the value of the maximum value of our tensor with the provided index from Tensor.argmax()
x[9]

tensor(91)

### Reshaping, view, stacking, squeezing, unsqueezing, and permute
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [67]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7) # Won't work because our reshaped tensor must be compatible with our original; cannot remove 2 elements from 9 -> 7
x_reshaped, x_reshaped.shape

RuntimeError: ignored

In [71]:
x_reshaped = x.reshape(1, 9) # Now will work because it is compatible
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Notice we added an extra dimension (extra set of `[ square brackets ]`)

In [74]:
x_reshaped = x.reshape(2, 9) # Cannot add 2 dimensions because it is not compatible; cannot double amount of elements from 9 -> 18
x_reshaped, x_reshaped.shape

RuntimeError: ignored

In [75]:
x_reshaped = x.reshape(9, 1) # Will work because it is compatible
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [76]:
x_reshaped = x.reshape(3, 3) # Still compatible because the total elements are still 9
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [77]:
# Change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [78]:
# View is similar to Reshape but a View shares a memory with the original tensor
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5 # Changed the 0th element to 5 on z but it also changes it on x
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [79]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [80]:
x_stacked = torch.stack([x, x, x, x], dim=1) # Changed dimension from 0 to 1 and they rearrange the values
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [82]:
x_stacked = torch.stack([x, x, x, x], dim=2) # Won't work because not compatible
x_stacked

IndexError: ignored

In [83]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped = x.reshape(1, 9)
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [84]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [87]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # image [ height, width, color_channels ]
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = torch.permute(x_original, [2, 0, 1]) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0
print(f"Previous shape: {x_original.shape}") # [ height, width, color_channels ]
print(f"New Shape: {x_permuted.shape}") # [ color_channels, height, width ]

Previous shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [102]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [103]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [105]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0, 0] # x[0][0] === x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [107]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [108]:
# You can aslo use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [109]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [110]:
# Get all values of 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [111]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [113]:
# Index on x to return 9
x[:, 2, 2], x[0, 2, 2], x[0][2][2]

(tensor([9]), tensor(9), tensor(9))

In [115]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])