# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [8]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [58]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7, 7))
random_tensor, random_tensor.shape

(tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
         [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
         [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
         [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
         [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
         [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
         [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [34]:
# Create another random tensor
random_tensor_2 = torch.rand(size=(1, 7))
random_tensor_2

# Perform matrix multiplication 
multiplied_tensor = torch.matmul(random_tensor, random_tensor_2.T)
multiplied_tensor, multiplied_tensor.size()

(tensor([[1.4950],
         [1.2665],
         [2.4300],
         [2.6885],
         [1.4732],
         [2.3238],
         [2.1837]]), torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [35]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(size=(7, 7))

torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(size=(1, 7))

# Matrix multiply tensors
multiplied_tensor_2 = torch.matmul(tensor_A, tensor_B.T)
multiplied_tensor_2, multiplied_tensor_2.size()

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]), torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [37]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [42]:
from torch.cuda import is_available
# Set random seed
GPU_RANDOM_SEED = torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(7, 7)).to(device)
tensor_B = torch.rand(size=(1, 7)).to(device)
tensor_A, tensor_B


Device: cuda


(tensor([[0.6186, 0.6962, 0.5300, 0.2560, 0.7366, 0.0204, 0.2036],
         [0.3748, 0.2564, 0.3251, 0.0902, 0.3936, 0.6069, 0.1743],
         [0.4743, 0.8579, 0.4486, 0.5139, 0.4569, 0.6012, 0.8179],
         [0.9736, 0.8175, 0.9747, 0.4638, 0.0508, 0.2630, 0.8405],
         [0.4968, 0.2515, 0.1168, 0.0321, 0.0780, 0.3986, 0.7742],
         [0.7703, 0.0178, 0.8119, 0.1087, 0.3943, 0.2973, 0.4037],
         [0.4018, 0.0513, 0.0683, 0.4218, 0.5065, 0.2729, 0.6883]],
        device='cuda:0'),
 tensor([[0.0500, 0.4663, 0.9397, 0.2961, 0.9515, 0.6811, 0.0488]],
        device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [45]:
# Perform matmul on tensor_A and tensor_B
z = torch.matmul(tensor_A, tensor_B.T)
z, z.size()

(tensor([[1.6540],
         [1.2669],
         [1.8815],
         [1.7516],
         [0.6448],
         [1.4392],
         [0.9344]], device='cuda:0'), torch.Size([7, 1]))

### 8. Find the maximum and minimum values of the output of 7.

In [46]:
# Find max
z_max = z.max()

# Find min
z_min = z.min()

z_max, z_min

(tensor(1.8815, device='cuda:0'), tensor(0.6448, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [49]:
# Find arg max
max_index = torch.argmax(z)

 
# Find arg min
min_index = torch.argmin(z)

max_index, min_index

(tensor(2, device='cuda:0'), tensor(4, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [64]:
# Set seed
RANDOM_SEED = torch.manual_seed(7)

# Create random tensor
rand_tensor = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
squeezed_tensor = rand_tensor.squeeze() # torch.squeeze(rand_tensor)

# Print out tensors and their shapes
print(rand_tensor, rand_tensor.size())
print(squeezed_tensor, squeezed_tensor.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
